<?php

namespace Flying\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AirportsAddedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirportsAddedRepository extends EntityRepository
{
}
