<?php

namespace Flying\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AirportsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirportsRepository extends EntityRepository
{
}
